global:
  namespace: ""
  noNamespace: false

externalSecrets:
  aws:
      # -- Region: The AWS region where the secret resides (default "us-east-1")
      region: "us-east-1"
      secretName:
        config: ""
        license: ""

ingress:
  hostname: "localhost.localdomain"
  class: "alb"
  # -- sslCertArn is only valid when using the 'alb' class. Leave empty for aut-select
  sslCertArn: ""
  # -- Uncomment below to add custom annotations for the public ingress
  annotations: {}

backend:
  image: ""
  disable: false
  v9: 
    tag: ""
    replicas: 1
    reloadOnUpgrade: false
  v10: 
    tag: ""
    replicas: 1
    reloadOnUpgrade: false

ui:
  image: ""
  tag: ""
  disable: false
  replicas: 1
  reloadOnUpgrade: false
  resources:
    memory: 1
    cpu: 1
  session:
    type: "filesystem"
    cookieDomain: "localhost.localdomain"
    oauthEnforceRoles: "true"
  env: {}
