apiVersion: v2
name: reveal-keycloak
description: Reveal Keycloak
type: application
version: 2.0.0
appVersion: "20.0.3"
maintainers:
- name: Reveal-Brainspace
  email: info@revealdata.com
  url: https://revealdata.com