apiVersion: v2
name: reveal-keycloak
description: Reveal Keycloak
type: application
version: 18.0.2
appVersion: "18.0.2.2"
maintainers:
- name: Reveal-Brainspace
  email: info@revealdata.com
  url: https://revealdata.com
