{{- if not .Values.global.NoNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace | default .Release.Name }}
  labels:
    application: "github-actions-controller"
{{- end }}