---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: github-actions-secret-store
  namespace: {{ .Release.Namespace }}
  labels:
    application: "github-actions-controller"
spec:
  provider:
    aws:
      service: SecretsManager
      region: "us-east-1"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-actions-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    application: "github-actions-controller"
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: github-actions-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.authSecret.name }}
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: {{ .Values.authSecret.key }}
        property: "token"
    - secretKey: github_webhook_secret_token
      remoteRef:
        key: {{ .Values.authSecret.key }}
        property: "webhook_token"