{{- if .Values.global.serviceAccount }}
{{- if .Values.global.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccount.name | default "actions-runner-sa" }}
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.global.serviceAccount.roleArn  }}

{{- end }}
{{- end }}