{{- if eq  .Values.secrets.provider "external-secrets" }}
{{- if eq  .Values.secrets.externalSecrets.provider "aws" }}
# Using AWS SecretsManager
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: reveal-cloud-ai-secret-store
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secrets.externalSecrets.aws.region | default "us-east-1" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: reveal-cloud-ai-secrets
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: reveal-cloud-ai-secret-store
    kind: SecretStore
  target:
    name: reveal-cloud-ai-secrets
    creationPolicy: Owner
  data:
    - secretKey: aws-access-key-id
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.aws_credentials }}
        property: "AWS_ACCESS_KEY_ID"

    - secretKey: aws-secret-access-key
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.aws_credentials }}
        property: "AWS_SECRET_ACCESS_KEY"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.mongodb.auth.existingSecret }}
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: reveal-cloud-ai-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.mongodb.auth.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: mongodb-passwords
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.mongodb_secrets }}
        property: "mongodb-passwords"

    - secretKey: mongodb-root-password
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.mongodb_secrets }}
        property: "mongodb-root-password"

    - secretKey: mongodb-metrics-password
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.mongodb_secrets }}
        property: "mongodb-metrics-password"

    - secretKey: mongodb-replica-set-key
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.mongodb_secrets }}
        property: "mongodb-replica-set-key"
{{- end }}
{{- end }}