---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reveal-cloud-ai-labeling
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  selector:
    matchLabels:
      app: deployment-reveal-cloud-ai-labeling
  progressDeadlineSeconds: 600
  replicas: {{ .Values.cloud_ai.services.labeling.replicas }}
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deployment-reveal-cloud-ai-labeling
      {{- if .Values.cloud_ai.reloadOnUpgrade }}
      annotations:
        timestamp: {{ now | quote }}
      {{- end }}
    spec:
      nodeSelector:
{{ $nodeSelector := mergeOverwrite .Values.cloud_ai.services.nodeSelector .Values.cloud_ai.services.labeling.nodeSelector }}
{{- toYaml $nodeSelector | indent 8 }}
      volumes:
      - name: ephemeral
        emptyDir:
          sizeLimit: 100Gi
      containers:
      - image: {{.Values.cloud_ai.services.labeling.image}}:{{.Values.cloud_ai.services.labeling.tag}}
        volumeMounts:
          - mountPath: {{ .Values.cloud_ai.services.api.storage.mountPath }}
            name: ephemeral
        envFrom:
        - configMapRef:
            name: "reveal-cloud-ai-env"
        env:
          - name: TARGET_APP
            value: "labeling"
{{- /* output env vars for Review secrets (_helpers.tpl) */}}
{{- include "resources.env.secrets" . | indent 6 }}
        resources:
{{ $resources := mergeOverwrite .Values.cloud_ai.services.resources .Values.cloud_ai.services.labeling.resources }}
{{- toYaml $resources | indent 10 }}
        imagePullPolicy: Always
        name: reveal-cloud-ai-labeling
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      tolerations:
{{ $tolerations := concat .Values.cloud_ai.services.tolerations .Values.cloud_ai.services.labeling.tolerations }}
{{- toYaml $tolerations | indent 8 }}
{{- if .Values.cloud_ai.services.labeling.PodDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.cloud_ai.services.labeling.PodDisruptionBudget.name }}
spec:
  selector:
    matchLabels:
      app: deployment-reveal-cloud-ai-labeling
{{- if .Values.cloud_ai.services.labeling.PodDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.cloud_ai.services.labeling.PodDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.cloud_ai.services.labeling.PodDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.cloud_ai.services.labeling.PodDisruptionBudget.maxUnavailable }}
{{- end }}
{{- end -}}