{{- if .Values.secrets.ServiceAccount }}
{{- if .Values.secrets.ServiceAccount.RoleArn }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-secrets-provider-sa
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.secrets.ServiceAccount.RoleArn  }}
{{- end }}{{- end }}

{{- if .Values.brains_ana.autoscale.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ana-scale-role-sa
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  {{- if eq .Values.secrets.provider "secrets-store-csi" }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.secrets.ServiceAccount.RoleArn  }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ana-scale-role
  namespace: {{ .Values.global.namespace | default .Release.Name }}
rules:
  - apiGroups: [ "", "apps" ]
    resources: [ "replicasets", "deployments", "deployments/scale", "pods" ]
    verbs: [ "get", "list", "patch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ana-scale-rolebind
  namespace: {{ .Values.global.namespace | default .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ana-scale-role
subjects:
- kind: ServiceAccount
  name: ana-scale-role-sa

{{- end }}