{{- if eq .Values.secrets.provider "kubernetes" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: brainspace-secrets
  namespace: {{ .Values.global.namespace | default .Release.Name }}
type: Opaque
data:
{{- range $key, $val := .Values.secrets.kubernetes }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}
{{- end }}