{{- if eq .Values.secrets.provider "kubernetes" }}
{{- range .Values.secrets.secretDefinitions }}
{{- if not .useExistingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .eksSecretName }}
  namespace: {{ $.Values.global.namespace | default $.Release.Name }}
type: Opaque
{{- if .data }}
data:
  {{- range .data }}
  {{- $defaults := index $.Values.defaults.secrets .secretKey }}
  {{- if and $defaults.value (not .value) }}
  {{ .secretKey }}: {{ index $defaults "value" | b64enc | quote }}
  {{- else }}
  {{ .secretKey }}: {{ .value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}