{{- if eq .Values.secrets.provider "secrets-store-csi" }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
   name: brainspace-secrets-provider
   namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: {{ .Values.secrets.secretsStoreCSI.secretArn }}
          objectType: "secretsmanager"
          jmesPath:
              - path: "host"
                objectAlias: "db-host"
              - path: "port"
                objectAlias: "db-port"
              - path: "database"
                objectAlias: "db-name"
              - path: "brainsDbUsername"
                objectAlias: "brainspace-db-user"
              - path: "brainsDbPassword"
                objectAlias: "brainspace-db-password"
  secretObjects:
    - secretName: brainspace-secrets
      type: Opaque
      data:
        - objectName: brainspace-db-user
          key: brainspace_db_user
        - objectName: brainspace-db-password
          key: brainspace_db_password
        - objectName: db-name
          key: brainspace_db_name
        - objectName: db-host
          key: brainspace_db_host
        - objectName: db-port
          key: brainspace_db_port
{{- end }}