---
{{ if eq .Values.storage.type "efs" }}
{{ if .Values.global.development }}
# Development Shared Data persistant volume (BRAINSPACE INTERNAL)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-devshared-fs-{{ .Release.Name }}
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-430d76b6::fsap-0c499aedc3e4451c0
---
## Development Shared Data Persistent claim (BRAINSPACE INTERNAL)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-devshared
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: efs-pv-devshared-fs-{{ .Values.global.namespace | default .Release.Name }}
  resources:
    requests:
      storage: 1Gi
{{ end }}
---
{{ if .Values.global.database.useContainer }}
## PostgreSQL data Persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-db-data-{{ .Values.storage.efs.FileSystemId }}-{{ .Values.storage.efs.dbAccessPointId }}
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.storage.efs.FileSystemId }}::{{ .Values.storage.efs.dbAccessPointId }}
---
## PostgreSQL data Persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-db-data
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  volumeName: efs-pv-db-data-{{ .Values.storage.efs.FileSystemId }}-{{ .Values.storage.efs.dbAccessPointId }}
  resources:
    requests:
      storage: 1Gi
{{ end }}
---
## Shared Logs Persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-logs-{{ .Values.storage.efs.FileSystemId }}-{{ .Values.storage.efs.logsAccessPointId }}
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.storage.efs.FileSystemId }}::{{ .Values.storage.efs.logsAccessPointId }}

---
## Shared Logs Persistent claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-logs
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: efs-pv-logs-{{ .Values.storage.efs.FileSystemId }}-{{ .Values.storage.efs.logsAccessPointId }}
  resources:
    requests:
      storage: 1Gi

---
## Shared /data Persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-data-{{ .Values.storage.efs.FileSystemId }}-{{ .Values.storage.efs.dataAccessPointId }}
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.storage.efs.FileSystemId }}::{{ .Values.storage.efs.dataAccessPointId }}

---
## Shared /data Persistent claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-data
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: efs-pv-data-{{ .Values.storage.efs.FileSystemId }}-{{ .Values.storage.efs.dataAccessPointId }}
  resources:
    requests:
      storage: 1Gi

---
## APP /localdata Persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-app-localdata-{{ .Values.storage.efs.FileSystemId }}-{{ .Values.storage.efs.localdataAccessPointId }}
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.storage.efs.FileSystemId }}::{{ .Values.storage.efs.localdataAccessPointId }}

---
## APP /localdata Persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-app-localdata
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: efs-pv-app-localdata-{{ .Values.storage.efs.FileSystemId }}-{{ .Values.storage.efs.localdataAccessPointId }}
  resources:
    requests:
      storage: 10Gi

---
## APP plugins Persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-app-plugins-{{ .Values.storage.efs.FileSystemId }}-{{ .Values.storage.efs.pluginsAccessPointId }}
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.storage.efs.FileSystemId }}::{{ .Values.storage.efs.pluginsAccessPointId }}

---
## APP plugins Persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-app-plugins
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  volumeName: efs-pv-app-plugins-{{ .Values.storage.efs.FileSystemId }}-{{ .Values.storage.efs.pluginsAccessPointId }}
  resources:
    requests:
      storage: 10Gi
{{ end }}
