---
# Deployment: brains-app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brains-app
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  labels:
    app.kubernetes.io/name: brains-app
    app.kubernetes.io/part-of: brainspace
    app.kubernetes.io/component: application
spec:
  selector:
    matchLabels:
      app: deployment-brains-app
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deployment-brains-app
      {{- if .Values.brains_app.reloadOnUpgrade }}
      annotations:
        timestamp: {{ now | quote }}
      {{- end }}
    spec:
      hostname: brains-app
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
        {{- if .Values.brains_app.nodeGroup }}
        eks.amazonaws.com/nodegroup: {{ .Values.brains_app.nodeGroup }}
        {{- end }}
      {{- if .Values.global.ecr }}{{- if .Values.global.ecr.secret }}
      imagePullSecrets:
      - name: {{ .Values.global.ecr.secret }}
      {{- end }} {{- end }}
      {{- if .Values.global.serviceAccount }}
      {{- if .Values.global.serviceAccount.roleArn }}
      serviceAccountName: {{ .Values.global.serviceAccount.name | default "brainspace-sa" }}
      {{- end }}{{- end }}
      volumes:
      {{- if or (eq .Values.storage.class "efs-sc") (eq .Values.storage.class "pvc") }}
      - name: log-path
        emptyDir: {}
      - name: plugins-data
        emptyDir: {}
      - name: shared-data
        persistentVolumeClaim:
          claimName: {{- if .Values.storage.pvc }} {{ .Values.storage.pvc.sharedData }} {{- else }} pvc-shared-data {{- end }}
      - name: app-localdata
        persistentVolumeClaim:
          claimName: {{- if .Values.storage.pvc }} {{ .Values.storage.pvc.appLocalData }} {{- else }} pvc-app-localdata {{- end }}
      - name: plugins-additional-data
        persistentVolumeClaim:
          claimName: {{- if .Values.storage.pvc }} {{ .Values.storage.pvc.appPlugins }} {{- else }} pvc-app-plugins {{- end }}
      - name: shared-logs
        persistentVolumeClaim:
          claimName: {{- if .Values.storage.pvc }} {{ .Values.storage.pvc.sharedLogs }} {{- else }} pvc-shared-logs {{- end }}
      - name: bt-data
        persistentVolumeClaim:
          claimName: {{- if .Values.storage.pvc }} {{ .Values.storage.pvc.BtData }} {{- else }} pvc-bt-data {{- end }}
      - name: basis-data
        persistentVolumeClaim:
          claimName: {{- if .Values.storage.pvc }} {{ .Values.storage.pvc.BasisData }} {{- else }} pvc-basis-data {{- end }}
      {{- else }}
      - name: bt-data
        emptyDir: {}
      - name: basis-data
        emptyDir: {}
      - name: plugins-data
        emptyDir: {}
      - name: shared-data
        emptyDir: {}
      - name: app-localdata
        emptyDir: {}
      - name: plugins-additional-data
        emptyDir: {}
      - name: shared-logs
        emptyDir: {}
      {{- end }}
      # Secrets Volumes
      {{- include "secrets.volumes" . | indent 6 }}
      initContainers:
      - name: brains-bt
        image: {{ .Values.brains_bt.image }}:{{ .Values.brains_bt.tag }}
        command: ["/bin/ash"]
        args: ["-c", "apk add rsync; rsync --delete -av --chown 1604:1604 /usr/data/{{ .Values.brains_bt.basis_dir }}/* /usr/data/vol/{{ .Values.brains_bt.basis_dir }}/ && rsync --delete -av --chown 1604:1604 /usr/data/BatchTools/* /usr/data/vol/BatchTools/"]
        imagePullPolicy: {{ .Values.brains_bt.imagePullPolicy | default "IfNotPresent" }}
        volumeMounts:
          - name: basis-data
            mountPath: /usr/data/vol/{{ .Values.brains_bt.basis_dir }}
          - name: bt-data
            mountPath: /usr/data/vol/BatchTools
        terminationMessagePolicy: FallbackToLogsOnError
      - name: brains-plugins
        image: {{ .Values.brains_app.plugins.image }}:{{ .Values.brains_app.plugins.tag }}
        command: ["/bin/ash"]
        args: ["-c", "apk add rsync; rsync --delete -av --chown 1604:1604 /plugins/* /fs-plugins/"]
        imagePullPolicy: {{ .Values.brains_app.plugins.imagePullPolicy | default "Always" }}
        volumeMounts:
          - name: plugins-data
            mountPath: /fs-plugins
        terminationMessagePolicy: FallbackToLogsOnError
      - name: brains-additional-plugins
        image: {{ .Values.brains_app.additionalPlugins.image }}:{{ .Values.brains_app.additionalPlugins.tag }}
        command: ["/bin/ash"]
        args: ["-c", "apk add rsync && rsync -av --chown 1604:1604 /plugins/* /fs-plugins/"]
        imagePullPolicy: {{ .Values.brains_app.additionalPlugins.imagePullPolicy | default "Always" }}
        volumeMounts:
          - name: plugins-additional-data
            mountPath: /fs-plugins
        terminationMessagePolicy: FallbackToLogsOnError
      containers:
      - name: brains-app
        image: {{ .Values.brains_app.image }}:{{ .Values.brains_app.tag }}
        imagePullPolicy: {{ .Values.brains_app.imagePullPolicy | default "Always" }}
        resources:
          requests:
          {{- include "resources.values" .Values.brains_app | indent 8 }}
          limits:
          {{- include "resources.values" .Values.brains_app | indent 8 }}
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: brains-config
        - configMapRef:
            name: brains-app-config
        env:
          {{- if not .Values.brains_app.jvmMemory.useContainerSupport }}
          {{- /* env vars for Java Resources (_helpers.tpl) */ -}}
          {{- include "java.resources.values" .Values.brains_app | indent 6 }}
          {{- else }}
          - name: CATALINA_OPTS
            value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage={{ .Values.brains_app.jvmMemory.MaxRAMPercentage }} -XX:MaxMetaspaceSize={{ .Values.brains_app.jvmMemory.MaxMetaspaceSize }}"
          {{- end }}
          {{- /* env vars for Brainspace secrets (_helpers.tpl) */}}
          {{- include "secrets.env" . |indent 6 }}
        lifecycle:
          postStart:
            exec:
              command: 
                - "/bin/bash"
                - "-c"
                - |
                  if [[ -e {{ .Values.brains_app.brainspaceLicenseFile }} ]]; then
                  cp {{ .Values.brains_app.brainspaceLicenseFile }} {{ .Values.brains_app.brainspaceHome }}/.brainspace/brainspace_license.txt;
                  fi;
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: basis-data
          readOnly: true
          mountPath: {{ .Values.brains_app.brainspaceHome }}/.brainspace/{{ .Values.brains_bt.basis_dir }}
        - name: bt-data
          readOnly: true
          mountPath: {{ .Values.brains_app.brainspaceHome }}/.brainspace/BatchTools
        - name: shared-data
          readOnly: false
          mountPath: /data
        - name: app-localdata
          readOnly: false
          mountPath: /localdata
        - name: plugins-data
          readOnly: false
          mountPath: {{ .Values.brains_app.brainspaceHome }}/.brainspace/plugins/default
        - name: plugins-additional-data
          readOnly: false
          mountPath: {{ .Values.brains_app.brainspaceHome }}/.brainspace/plugins/additional
        - name: shared-logs
          readOnly: false
          mountPath: {{ .Values.brains_app.brainspaceLogs }}
          subPath: {{ .Values.brains_app.logDir | default "app" }}
        # Secrets Volume Mounts
        {{- include "secrets.volumes.mounts" . | indent 8 }}
      - name: brainspace-log
        image: busybox:1.28
        args: [ /bin/sh, -c, 'tail -n+1 -F /var/log/brainspace.log' ]
        volumeMounts:
        - name: shared-logs
          mountPath: /var/log
          readOnly: true
          subPath: {{ .Values.brains_app.logDir | default "app" }}
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 120
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
      - effect: "NoSchedule"
        key: "linux_large_brs"
        operator: "Exists"
      {{- if .Values.brains_app.tolerations }}
{{ toYaml .Values.brains_app.tolerations | indent 6}}
      {{- end }}
        

---
apiVersion: v1
kind: Service
metadata:
  name: brains-app
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  annotations:
    #  Health check path annotations
    alb.ingress.kubernetes.io/healthcheck-path: /rest/ping
    alb.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  type: NodePort
  selector:
    app: deployment-brains-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

{{- if .Values.PodDisruptionBudget_app.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.PodDisruptionBudget_app.name }}
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  labels:
    app.kubernetes.io/part-of: brainspace
spec:
  selector:
    matchLabels:
      app: deployment-brains-app
{{- if .Values.PodDisruptionBudget_app.minAvailable }}
  minAvailable: {{ .Values.PodDisruptionBudget_app.minAvailable }}
{{- end }}
{{- if .Values.PodDisruptionBudget_app.maxUnavailable }}
  maxUnavailable: {{ .Values.PodDisruptionBudget_app.maxUnavailable }}
{{- end }}
{{- end -}}