{{- $ingress_class := (.Values.ingress.class | default "alb") -}}
{{- if eq $ingress_class "nginx" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  name: brains-ui
  annotations:
    # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/ingress/annotations/
    kubernetes.io/ingress.class: {{ $ingress_class }}
    
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    {{ if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations }}
    {{- end }}

spec:
  # Needed for nginx ingress for some reason. It doesn't like not having a default backend.
  defaultBackend:
    service:
      name: brains-ui
      port:
        number: 443
  rules:
    - host: {{ .Values.ingress.hostname | default "brainspace.docker.internal" }}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: brains-ui
                port:
                  number: 443
{{- end }}