---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace | default .Release.Name }}
  {{- if .Values.upgrade.extra_annotations }}
  annotations:
    {{- range $key, $value := .Values.upgrade.extra_annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.upgrade.extra_labels }}
  labels:
    {{- range $key, $value := .Values.upgrade.extra_labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
