---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.upgrade.service_account_name }}
  {{- if .Values.upgrade.extra_annotations }}
  annotations:
    {{- range $key, $value := .Values.upgrade.extra_annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.upgrade.extra_labels }}
  labels:
    {{- range $key, $value := .Values.upgrade.extra_labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
rules:
  - apiGroups: [ "", "apps" ]
    resources: [ "secrets",  "configmaps" ]
    verbs: [ "*" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "list" ]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.upgrade.service_account_name }}
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  {{- if .Values.upgrade.extra_annotations }}
  annotations:
    {{- range $key, $value := .Values.upgrade.extra_annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.upgrade.extra_labels }}
  labels:
    {{- range $key, $value := .Values.upgrade.extra_labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.upgrade.service_account_name }}
  {{- if .Values.upgrade.extra_annotations }}
  annotations:
    {{- range $key, $value := .Values.upgrade.extra_annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.upgrade.extra_labels }}
  labels:
    {{- range $key, $value := .Values.upgrade.extra_labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.upgrade.service_account_name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.upgrade.service_account_name }}
  namespace: {{ .Values.global.namespace | default .Release.Name }}
