---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: selenium-hub-secret-store
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  labels:
    application: selenium-grid
spec:
  provider:
    aws:
      service: SecretsManager
      region: "us-east-1"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: selenium-hub-config-toml
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  labels:
    application: selenium-grid
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: selenium-hub-secret-store
    kind: SecretStore
  target:
    name: selenium-hub-config-toml
    creationPolicy: Owner
  data:
    - secretKey: config.toml
      remoteRef:
        key: selenium/config