# Selenium Hub Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: selenium-hub-config
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  labels:
    application: "selenium-grid"
data:
  SE_OPTS: "--log-level FINE"

{{ if .Values.selenium.hub.env }}
{{- toYaml .Values.selenium.hub.env | indent 2 }}
{{- end }}
---
# Selenium Nodes Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: selenium-node-config
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  labels:
    application: "selenium-grid"
data:
  SE_EVENT_BUS_HOST: "selenium-srv"
  SE_EVENT_BUS_PUBLISH_PORT: "4442"
  SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
  SE_SCREEN_WIDTH: {{ .Values.selenium.nodes.screen.width | quote | default "2880" }}
  SE_SCREEN_HEIGHT: {{ .Values.selenium.nodes.screen.height | quote | default "1800" }}
  SE_SCREEN_DEPTH: {{ .Values.selenium.nodes.screen.depth | quote | default "24" }}
  SE_NODE_MAX_SESSIONS: {{ .Values.selenium.nodes.maxSessions | quote }}
{{ if .Values.selenium.nodes.env }}
{{- toYaml .Values.selenium.nodes.env | indent 2 }}
{{- end }}