---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-firefox
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  replicas: {{ .Values.selenium.nodes.firefox.replicas }}
  selector:
    matchLabels:
      app: node-firefox
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: node-firefox
      labels:
        app: node-firefox
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      containers:
        - name: node-firefox
          image: selenium/node-firefox:{{ .Values.selenium.nodes.firefox.version | default .Values.selenium.version }}
          resources:
{{ .Values.selenium.nodes.resources | toYaml | indent 12 }}
          ports:
            - containerPort: 5555
              name: node-firefox
          envFrom:
          - configMapRef:
              name: selenium-node-config