{{- $zoneIdFilters := (.Values.externalDns.zoneIdFilters) | fromYaml }}
{{- if and (.Values.externalDns) (.Values.externalDns.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: eks-blueprints-add-ons/add-ons/external-dns
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        external-dns:
          enable: {{ .Values.externalDns.enable }}
          serviceAccountName: {{ .Values.externalDns.serviceAccountName }}
      parameters:
      - name: external-dns.aws.region
        value: {{ .Values.region }}
      - name: external-dns.serviceAccount.name
        value: {{ .Values.externalDns.serviceAccountName }}
      - name: external-dns.interval
        value: "5m"
{{- range $index, $zone := ( $zoneIdFilters.zoneIdFilters )}}
      - name: external-dns.zoneIdFilters[{{ $index }}]
        value: {{ $zone }}
{{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
