---
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.reveal_samba.namespace}}

---
apiVersion: v1
kind: ConfigMap
data:
  # Note that the indentation here can get quite funky. So be careful with this method of pulling in
  # the block object from values.yaml
{{ toYaml .Values.reveal_samba.configmap | indent 2 }}
metadata:
  name: "reveal-samba"
  namespace: {{.Values.reveal_samba.namespace}}
