---
apiVersion: v1
kind: Service
metadata:
  name: service-reveal-samba-static
  namespace: {{.Values.reveal_samba.namespace}}

spec:
  type: ClusterIP
  clusterIP: 172.20.20.20
  selector:
    app: deployment-reveal-samba
  ports:
    - name: http
      protocol: TCP
      port: 445
      targetPort: 445
