{{- if eq  .Values.secrets.provider "external-secrets" }}
{{- if eq  .Values.secrets.externalSecrets.provider "aws" }}
# Using AWS SecretsManager
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: review-secret-store
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  provider:
    aws:
      service: SecretsManager
      {{- if .Values.secrets.serviceAccount }}
      {{- if .Values.secrets.serviceAccount.roleArn }}
      role: {{ .Values.secrets.serviceAccount.roleArn | quote }}
      {{- end }}{{- end }}
      region: {{ .Values.secrets.externalSecrets.aws.Region | default "us-east-1" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: review-secrets
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: review-secret-store
    kind: SecretStore
  target:
    name: review-secrets
    creationPolicy: Owner
  data:
    - secretKey: review-sql-server
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.reviewDatabase }}
        property: "review-sql-server"

    - secretKey: review-user-management-db
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.reviewDatabase }}
        property: "review-user-management-db"

    - secretKey: review-sql-auth-method
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.reviewDatabase }}
        property: "review-sql-auth-method"

    - secretKey: review-sql-username
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.reviewDatabase }}
        property: "review-sql-username"

    - secretKey: review-sql-password
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.reviewDatabase }}
        property: "review-sql-password"

    # Needs to be [0-9A-Z]{48}
    - secretKey: review-website-decryption-key
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.reviewWebEncryption }}
        property: "review-website-decryption-key"

    # Needs to be [0-9A-Z]{128}
    - secretKey: review-website-validation-key
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.reviewWebEncryption }}
        property: "review-website-validation-key"

    - secretKey: rabbitmq-username
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.rabbitmq }}
        property: "username"

    - secretKey: rabbitmq-password
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.rabbitmq }}
        property: "password"

    - secretKey: rabbitmq-amqp
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.rabbitmq }}
        property: "amqp"

    - secretKey: rabbitmq-vhost
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.rabbitmq }}
        property: "vhost"

{{- end }}
{{- end }}