---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-web
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  labels:
{{ $labels :=  mergeOverwrite .Values.review.labels .Values.review.web.labels }}
{{- toYaml $labels | indent 4 }}
spec:
  selector:
    matchLabels:
      app: deployment-review-web
  progressDeadlineSeconds: 600
  replicas: {{ .Values.review.web.replicas | default 1 }}
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deployment-review-web
      {{- if .Values.review.reloadOnUpgrade }}
      annotations:
        timestamp: {{ now | quote }}
      {{- end }}
    spec:
      nodeSelector:
{{ $nodeSelector := mergeOverwrite .Values.review.nodeSelector.windows .Values.review.web.nodeSelector }}
{{- toYaml $nodeSelector | indent 8 }}
      {{- if .Values.review.web.volumes }}
      volumes:
{{ toYaml .Values.review.web.volumes | indent 8 }}
      {{- end }}
      containers:
      - image: {{.Values.review.web.image}}:{{.Values.review.web.tag}}
        {{- if .Values.review.web.livenessProbe }}
        livenessProbe:
        {{- $livenessProbe := deepCopy .Values.review.web.livenessProbe }}
{{ toYaml .Values.review.web.livenessProbe | indent 10 }}
        {{- end }}
        ports:
        - containerPort: 443
        envFrom:
        - configMapRef:
            name: "review-env"
        env:
{{- /* output env vars for Review secrets (_helpers.tpl) */}}
{{- include "resources.env.secrets" . | indent 6 }}
        resources:
{{ toYaml .Values.review.web.resources | indent 10 }}
        imagePullPolicy: Always
        name: review-web
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        {{- if .Values.review.web.args }}
        args:
          {{ toYaml .Values.review.web.args | nindent 8 }}
        {{- end }}
        {{- if .Values.review.web.command }}
        command:
          {{ toYaml .Values.review.web.command | nindent 8 }}
        {{- end }}
        {{- if .Values.review.web.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.review.web.volumeMounts | indent 8 }}
        {{- end }}
      {{- if .Values.review.web.additionalContainers }}
{{ toYaml .Values.review.web.additionalContainers | indent 6 }}
      {{- end }}
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      tolerations:
{{ $tolerations := concat .Values.review.tolerations.windows .Values.review.web.tolerations }}
{{- toYaml $tolerations | indent 8 }}

---
apiVersion: v1
kind: Service
metadata:
  name: service-review-web
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-path: /Reveal/AuthorizationPages/LoginNotAuthorized.aspx
    alb.ingress.kubernetes.io/success-codes: 200-302

spec:
  selector:
    app: deployment-review-web
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
{{/*{{- if .Values.review.web.PodDisruptionBudget.enabled | default false }}*/}}
{{/*---*/}}
{{/*apiVersion: policy/v1*/}}
{{/*kind: PodDisruptionBudget*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Values.review.web.PodDisruptionBudget.name }}*/}}
{{/*spec:*/}}
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      app: deployment-review-web*/}}
{{/*{{- if .Values.review.web.PodDisruptionBudget.minAvailable }}*/}}
{{/*  minAvailable: {{ .Values.review.web.PodDisruptionBudget.minAvailable }}*/}}
{{/*{{- end }}*/}}
{{/*{{- if .Values.review.web.PodDisruptionBudget.maxUnavailable }}*/}}
{{/*  maxUnavailable: {{ .Values.review.web.PodDisruptionBudget.maxUnavailable }}*/}}
{{/*{{- end }}*/}}
{{/*{{- end -}}*/}}