---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-search-api
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  labels:
{{ $labels :=  mergeOverwrite .Values.review.labels .Values.review.ui.labels }}
{{- toYaml $labels | indent 4 }}
spec:
  selector:
    matchLabels:
      app: deployment-review-search-api
  progressDeadlineSeconds: 600
  replicas: {{ .Values.review.search_api.replicas | default 1 }}
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deployment-review-search-api
      {{- if .Values.review.reloadOnUpgrade }}
      annotations:
        timestamp: {{ now | quote }}
      {{- end }}
    spec:
      nodeSelector:
{{ $nodeSelector := mergeOverwrite .Values.review.nodeSelector.linux .Values.review.search_api.nodeSelector }}
{{- toYaml $nodeSelector | indent 8 }}
      containers:
      - image: {{.Values.review.search_api.image}}:{{.Values.review.search_api.tag}}
        ports:
        - containerPort: 443
        envFrom:
        - configMapRef:
            name: "review-env"
        env:
{{- /* output env vars for Review secrets (_helpers.tpl) */}}
{{- include "resources.env.secrets" . | indent 6 }}
        resources:
{{ toYaml .Values.review.search_api.resources | nindent 10 }}
        imagePullPolicy: Always
        name: review-search-api
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        {{- if .Values.review.search_api.args }}
        args:
          {{ toYaml .Values.review.search_api.args | nindent 8 }}
        {{- end }}
        {{- if .Values.review.search_api.command }}
        command:
          {{ toYaml .Values.review.search_api.command | nindent 8 }}
        {{- end }}
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      tolerations:
{{ $tolerations := concat .Values.review.tolerations.linux .Values.review.api.tolerations }}
{{- toYaml $tolerations | indent 8 }}

---
apiVersion: v1
kind: Service
metadata:
  name: service-review-search-api
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP

spec:
  selector:
    app: deployment-review-search-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

{{/*{{- if .Values.review.search_api.PodDisruptionBudget.enabled | default false }}*/}}
{{/*---*/}}
{{/*apiVersion: policy/v1*/}}
{{/*kind: PodDisruptionBudget*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Values.review.search_api.PodDisruptionBudget.name }}*/}}
{{/*spec:*/}}
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      app: deployment-review-search-api*/}}
{{/*{{- if .Values.review.search_api.PodDisruptionBudget.minAvailable }}*/}}
{{/*  minAvailable: {{ .Values.review.search_api.PodDisruptionBudget.minAvailable }}*/}}
{{/*{{- end }}*/}}
{{/*{{- if .Values.review.search_api.PodDisruptionBudget.maxUnavailable }}*/}}
{{/*  maxUnavailable: {{ .Values.review.search_api.PodDisruptionBudget.maxUnavailable }}*/}}
{{/*{{- end }}*/}}
{{/*{{- end -}}*/}}