{{- if .Values.ingress.enabled }}
{{- $ingress_class := (.Values.ingress.class | default "alb") -}}
{{- if (contains  "nginx" $ingress_class) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  name: review-ingress
  annotations:
    {{- if .Values.ingress.hostname }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.hostname }}
    {{- end }}
    kubernetes.io/ingress.class: {{ $ingress_class }}
    # Nginx ingress (nginx)
    # https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "http_503"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/upstream-vhost: {{ quote .Values.ingress.hostname }}
    {{- if .Values.ingress.annotations }}
    # Custom annotations
{{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  defaultBackend:
    service:
      name: service-review-series11-ui
      port:
        number: {{ .Values.ingress.backend.port | default 8443 }}
  rules:
    {{- if eq $ingress_class "nginx" }}
    - host: {{ .Values.ingress.hostname }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /
            pathType:  Prefix
            backend:
              service:
                name: service-review-series11-ui
                port:
                  number: {{ .Values.ingress.backend.port | default 8443 }}

{{- end }}
{{- end }}
