apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-otel-eks-sidecar
  namespace: aws-otel-eks
  labels:
    name: aws-otel-eks-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aws-otel-eks-sidecar
  template:
    metadata:
      labels:
        name: aws-otel-eks-sidecar
    spec:
      containers:
        - name: aws-otel-emitter
          image: public.ecr.aws/g9c4k4i4/trace-emitter:1
          env:
            - name: OTEL_OTLP_ENDPOINT
              value: {{ .Values.otelEndpoint }}
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: {{ .Values.otenResourceAttributes}}
            - name: S3_REGION
              value: {{ .Values.region }}
          imagePullPolicy: Always
        - name: aws-otel-collector
          image: "public.ecr.aws/aws-observability/aws-otel-collector:latest"
          env:
            - name: AWS_REGION
              value: {{ .Values.awsRegion }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests:
              cpu: 32m
              memory: 24Mi
