---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.crush_ftp.services.api.storage.name }}-pvc
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.crush_ftp.services.api.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.crush_ftp.services.api.storage.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reveal-crushftp-api
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  selector:
    matchLabels:
      app: deployment-reveal-crushftp-api
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deployment-reveal-crushftp-api
      {{- if .Values.crush_ftp.reloadOnUpgrade }}
      annotations:
        timestamp: {{ now | quote }}
      {{- end }}
    spec:
      nodeSelector:
{{ $nodeSelector := mergeOverwrite .Values.crush_ftp.services.nodeSelector .Values.crush_ftp.services.api.nodeSelector }}
{{- toYaml $nodeSelector | indent 8 }}
      volumes:
        - name: {{ .Values.crush_ftp.services.api.storage.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.crush_ftp.services.api.storage.name }}-pvc
      containers:
      - image: {{.Values.crush_ftp.services.api.image}}:{{.Values.crush_ftp.services.api.tag}}
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: {{ .Values.crush_ftp.services.api.storage.mountPath }}
            name: {{ .Values.crush_ftp.services.api.storage.name }}
        envFrom:
        - configMapRef:
            name: "reveal-crushftp-env"
        env:
          - name: TARGET_APP
            value: "api"
          # Expect this secret to be populated by the mongodb deployment.
          - name: mongoPassword
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mongodb
                key: mongodb-root-password
{{- /* output env vars for Review secrets (_helpers.tpl) */}}
{{- include "resources.env.secrets" . | indent 6 }}
        resources:
{{ $resources := mergeOverwrite .Values.crush_ftp.services.resources .Values.crush_ftp.services.api.resources }}
{{- toYaml $resources | indent 10 }}
        imagePullPolicy: Always
        name: reveal-crushftp-api
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      tolerations:
{{ $tolerations := concat .Values.crush_ftp.services.tolerations .Values.crush_ftp.services.api.tolerations }}
{{- toYaml $tolerations | indent 8 }}

---
apiVersion: v1
kind: Service
metadata:
  name: service-reveal-crushftp-api
  namespace: {{ .Values.global.namespace | default .Release.Name }}

spec:
  selector:
    app: deployment-reveal-crushftp-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
