{{- if .Values.global.makeNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace | default .Release.Name }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
data:
  # Note that the indentation here can get quite funky. So be careful with this method of pulling in
  # the block object from values.yaml
{{ toYaml .Values.processing_automation.config_values | indent 2 }}
metadata:
  name: "processing-automation-env"
  namespace: {{ .Values.global.namespace | default .Release.Name }}
