{{- if eq  .Values.secrets.provider "external-secrets" }}
{{- if eq  .Values.secrets.externalSecrets.provider "aws" }}
# Using AWS SecretsManager
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: processing-automation-secret-store
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secrets.externalSecrets.aws.region | default "us-east-1" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: processing-automation-secrets
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: processing-automation-secret-store
    kind: SecretStore
  target:
    name: processing-automation-secrets
    creationPolicy: Owner
  data:
    - secretKey: aws-access-key-id
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.aws_credentials }}
        property: "access_key_id"

    - secretKey: aws-secret-access-key
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.aws_credentials }}
        property: "secret_access_key"

    - secretKey: database-server
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.database_credentials }}
        property: "sql-hostname"

    - secretKey: database-username
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.database_credentials }}
        property: "sql-username"

    - secretKey: database-password
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.database_credentials }}
        property: "sql-password"
{{- end }}
{{- end }}