---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-automation
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  selector:
    matchLabels:
      app: deployment-processing-automation
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deployment-processing-automation
      {{- if .Values.processing_automation.reloadOnUpgrade }}
      annotations:
        timestamp: {{ now | quote }}
      {{- end }}
    spec:
      nodeSelector:
{{ toYaml .Values.processing_automation.nodeSelector | indent 8 }}
      containers:
      - image: {{.Values.processing_automation.image}}:{{.Values.processing_automation.tag}}
        envFrom:
        - configMapRef:
            name: "processing-automation-env"
        env:
{{- /* output env vars for Review secrets (_helpers.tpl) */}}
{{- include "resources.env.secrets" . | indent 6 }}
        resources:
{{ toYaml .Values.processing_automation.resources | indent 10 }}
        imagePullPolicy: Always
        name: processing-automation
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      tolerations:
{{ toYaml .Values.processing_automation.tolerations | indent 8 }}
{{- if .Values.PodDisruptionBudgetProcessing_automation.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.PodDisruptionBudgetProcessing_automation.name }}
spec:
  selector:
    matchLabels:
      app: deployment-processing-automation
{{- if .Values.PodDisruptionBudgetProcessing_automation.minAvailable }}
  minAvailable: {{ .Values.PodDisruptionBudgetProcessing_automation.minAvailable }}
{{- end }}
{{- if .Values.PodDisruptionBudgetProcessing_automation.maxUnavailable }}
  maxUnavailable: {{ .Values.PodDisruptionBudgetProcessing_automation.maxUnavailable }}
{{- end }}
{{- end -}}