{{- if .Values.keycloak.cacerts }}
{{- if .Values.keycloak.cacerts.enabled }}
{{- $cacerts_path := (.Values.keycloak.cacerts.path | default "cacerts") -}}
---
# Keycloak Trusted CA Certs
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-cacerts
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  labels:
    cacerts_path: {{ $cacerts_path | quote }}
type: Opaque
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob (printf "%s/*.pem" $cacerts_path) }}
  {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
  {{- end }}
{{- end }}

{{- if .Values.global.ecr.enabled }}
{{- $region := (.Values.global.ecr.region | default "us-east-1") }}
{{- $account := (.Values.global.ecr.account | default "053522176595") }}
{{- $server := (.Values.global.ecr.host | default (printf "%s.dkr.ecr.%s.amazonaws.com" $account $region)) }}
{{- $username := (.Values.global.ecr.username | default "AWS") }}
{{- $password := (.Values.global.ecr.password | default "NULL") }}
{{- $secretValue := printf "{\"auths\": {\"%s\": {\"username\": \"%s\", \"password\": \"%s\" } } }" $server $username $password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "aws-ecr-credentials"
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  labels:
    ecr.host: {{ $server }}
    ecr.user: {{ $username }}
type: kubernetes.io/dockerconfigjson
data:
  
  .dockerconfigjson: {{ $secretValue | b64enc | quote}}
{{- end }}
{{- end }}
