{{- if eq .Values.secrets.provider "external-secrets" }}
{{- if eq .Values.secrets.externalSecrets.provider "azurekv" }}
# Using Azure KeyVault
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-sp
  namespace: {{ .Values.global.namespace | default .Release.Name }}
type: Opaque
data:
  ClientID: {{ .Values.secrets.ExternalSecrets.azurekv.auth.ClientID | b64enc }}
  ClientSecret: {{ .Values.secrets.ExternalSecrets.azurekv.auth.ClientSecret | b64enc }}

---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: keycloak-secret-store
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  provider:
    azurekv:
      tenantId: {{ .Values.secrets.ExternalSecrets.azurekv.TennantId | quote }}
      vaultUrl: {{ .Values.secrets.ExternalSecrets.azurekv.VaultUrl | quote }}
      authSecretRef:
        clientId:
          name: keycloak-sp
          key: ClientID
        clientSecret:
          name: keycloak-sp
          key: ClientSecret
---
apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: keycloak-secret-store
    kind: SecretStore
  target:
    name: keycloak-secrets
    creationPolicy: Owner
  data:
    - secretKey: keycloak_admin_user
      remoteRef:
          key: kc-admin-user
    - secretKey: keycloak_admin_password
      remoteRef:
          key: kc-admin-password
    - secretKey: kc_db_url_host
      remoteRef:
        key: kc-db-url-host
    - secretKey: kc_db_url_port
      remoteRef:
        key: kc-db-url-port
    - secretKey: kc_db
      remoteRef:
        key: kc-db
    - secretKey: kc_db_url_database
      remoteRef:
        key: kc-db-url-database
    - secretKey: kc_db_username
      remoteRef:
        key: kc-db-username
    - secretKey: kc_db_password
      remoteRef:
        key: kc-db-password
{{- end }}
{{- end }}