{{- if eq  .Values.secrets.provider "external-secrets" }}
{{- if eq  .Values.secrets.externalSecrets.provider "aws" }}
# Using AWS SecretsManager
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: keycloak-secret-store
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  provider:
    aws:
      service: SecretsManager
      {{- if .Values.secrets.serviceAccount }}
      {{- if .Values.secrets.serviceAccount.roleArn }}
      role: {{ .Values.secrets.serviceAccount.roleArn | quote }}
      {{- end }}{{- end }}
      region: {{ .Values.secrets.externalSecrets.aws.region | default "us-east-1" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: keycloak-secret-store
    kind: SecretStore
  target:
    name: keycloak-secrets
    creationPolicy: Owner
  data:
    - secretKey: keycloak_admin_user
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.admin | default "keycloak/user/admin" }}
        property: "username"
    - secretKey: keycloak_admin_password
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.admin | default "keycloak/user/admin" }}
        property: "password"
    - secretKey: kc_db_url_host
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.database | default "keycloak/database/master" }}
        property: "host"
    - secretKey: kc_db_url_port
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.database | default "keycloak/database/master" }}
        property: "port"
    - secretKey: kc_db
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.database | default "keycloak/database/master" }}
        property: "engine"
    - secretKey: kc_db_url_database
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.database | default "keycloak/database/master" }}
        property: "dbname"
    - secretKey: kc_db_username
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.database | default "keycloak/database/master" }}
        property: "username"
    - secretKey: kc_db_password
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.database | default "keycloak/database/master" }}
        property: "password"
{{- end }}
{{- end }}