{{- if eq  .Values.secrets.provider "secrets-store-csi" }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
   name: keycloak-secrets-provider
   namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: {{ .Values.secrets.SecretsStoreCSI.secretArn.admin | default "keycloak/user/admin" }}
          objectType: "secretsmanager"
          jmesPath:
              - path: "username"
                objectAlias: "keycloak-admin-user"
              - path: "password"
                objectAlias: "keycloak-admin-password"
        - objectName: {{ .Values.secrets.SecretsStoreCSI.secretArn.database | default "keycloak/database/master" }}
          objectType: "secretsmanager"
          jmesPath:
              - path: "username"
                objectAlias: "kc-db-username"
              - path: "password"
                objectAlias: "kc-db-password"
              - path: "engine"
                objectAlias: "kc-db"
              - path: "host"
                objectAlias: "kc-db-url-host"
              - path: "dbname"
                objectAlias: "kc-db-url-database"
  secretObjects:
  - secretName: keycloak-secrets
    type: Opaque
    data:
      - objectName: keycloak-admin-user
        key: keycloak_admin_user
      - objectName: keycloak-admin-password
        key: keycloak_admin_password
      - objectName: kc-db-username
        key: kc_db_username
      - objectName: kc-db-password
        key: kc_db_password
      - objectName: kc-db
        key: kc_db
      - objectName: kc-db-url-host
        key: kc_db_url_host
      - objectName: kc-db-url-database
        key: kc_db_url_database
{{- end }}