{{- if .Values.secrets.serviceAccount }}
{{- if .Values.secrets.serviceAccount.roleArn }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-secrets-provider-sa
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.secrets.serviceAccount.roleArn }}

{{- end }}{{- end }}