---
# Deployment: keycloak-proxy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-proxy
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  labels:
    app.kubernetes.io/name: keycloak-proxy
    app.kubernetes.io/part-of: keycloak
    app.kubernetes.io/component: application
spec:
  selector:
    matchLabels:
      app: keycloak-proxy
  progressDeadlineSeconds: 600
  replicas: {{ .Values.keycloak.proxy.replicas | default 1 }}
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: keycloak-proxy
      {{- if .Values.keycloak.reloadOnUpgrade }}
      annotations:
        timestamp: {{ now | quote }}
      {{- end }}
    spec:
      hostname: keycloak
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
        {{- if .Values.keycloak.proxy.nodegroup }}
        alpha.eksctl.io/nodegroup-name: {{ .Values.keycloak.proxy.nodegroup }}
        {{- end }}
      
      volumes:
        # Keycloak Proxy Security Secret
        - name: {{ .Values.keycloak.proxy.security.configMapName | default "keycloak-proxy-security" }}-vol
          secret:
            secretName: {{ .Values.keycloak.proxy.security.configMapName | default "keycloak-proxy-security" }}
            optional: true

      {{- if .Values.global.ecr.enabled }}
      imagePullSecrets:
      - name: aws-ecr-credentials
      {{- end }}
      containers:
      - name: keycloak
        image: {{ .Values.keycloak.proxy.image }}:{{ .Values.keycloak.proxy.tag | default "latest" }}
        imagePullPolicy: {{ .Values.keycloak.proxy.imagePullPolicy | default "Always" }}
        {{- if .Values.keycloak.proxy.resources }}
        resources:
{{ toYaml .Values.keycloak.proxy.resources | indent 10 }}
        {{- end }}
        ports:
          - name: liveness-port
            containerPort: 8080
          - containerPort: 8443
        startupProbe:
          failureThreshold: 2
          periodSeconds: 10
          httpGet:
            path: /health/ready
            port: liveness-port
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 15
          successThreshold: 1
          httpGet:
            path: /health/ready
            port: liveness-port
        volumeMounts:
          - name: {{ .Values.keycloak.proxy.security.configMapName | default "keycloak-proxy-security" }}-vol
            mountPath: /run/security
        envFrom:
        - configMapRef:
            name: keycloak-proxy-config
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 60
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
        {{- if .Values.keycloak.proxy.tolerations }}
{{ toYaml .Values.keycloak.proxy.tolerations | indent 6}}
        {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-proxy
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  annotations:
    #  Health check path annotations
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  type: NodePort
  selector:
    app: keycloak-proxy
  ports:
    - name: http
      protocol: TCP
      port: 8443
      targetPort: 8443
---

{{- if .Values.PodDisruptionBudgetkeycloakproxy.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.PodDisruptionBudgetkeycloakproxy.name }}
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  selector:
    matchLabels:
      app: keycloak-proxy
{{- if .Values.PodDisruptionBudgetkeycloakproxy.minAvailable }}
  minAvailable: {{ .Values.PodDisruptionBudgetkeycloakproxy.minAvailable }}
{{- end }}
{{- if .Values.PodDisruptionBudgetkeycloakproxy.maxUnavailable }}
  maxUnavailable: {{ .Values.PodDisruptionBudgetkeycloakproxy.maxUnavailable }}
{{- end }}
{{- end -}}
