{{- if .Values.ingress.admin.enabled }}
{{- $ingress_class := (.Values.ingress.admin.class | default "alb") -}}
{{- $service_port := (.Values.ingress.backend.port | default 8443) -}}
{{- if eq .Values.ingress.admin.class "alb" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  name: keycloak-admin-internal
  annotations:
    {{- if .Values.ingress.admin.hostname }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.admin.hostname }}
    {{- end }}
    kubernetes.io/ingress.class: {{ $ingress_class }}
    # AWS ALB ingress (alb)
    # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/ingress/annotations/
    alb.ingress.kubernetes.io/target-type: ip
    {{- if .Values.ingress.admin.class_alb.ipv6 }}
    alb.ingress.kubernetes.io/ip-address-type: dualstack
    {{- end }}
    alb.ingress.kubernetes.io/scheme: "internal"
    #  Health check path annotations
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "4"
    # The ARN of your SSL certificate.
    {{- if .Values.ingress.admin.class_alb.sslCertArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.admin.class_alb.sslCertArn }}
    # SSL Redirect Setting
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    {{- end }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'

    {{- if .Values.ingress.admin.class_alb.attributes -}}
    {{- $attributes := list }}
    {{- range .Values.ingress.admin.class_alb.attributes }}
    {{- $attributes = append $attributes (printf "%s=%s" .key .value) }}
    {{- end }}
    # Load-balancer Attributes
    alb.ingress.kubernetes.io/load-balancer-attributes: "{{ join "," $attributes }}"
    {{- end }}

    {{- if .Values.ingress.admin.annotations }}
    # Custom annotations
{{- toYaml .Values.ingress.admin.annotations | nindent 4 }}
    {{- end }}
spec:
  defaultBackend:
    service:
      name: keycloak-proxy
      port:
        number: 8443
  rules:
    - http:
        paths:
          {{- if .Values.ingress.admin.class_alb.sslCertArn }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-proxy
                port:
                  number: {{ $service_port }}
{{- end }}
{{- end }}