{{- if .Values.ingress.public.enabled }}
{{- $ingress_class := (.Values.ingress.public.class | default "alb") -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  name: keycloak-ui
  annotations:
    {{- if .Values.ingress.public.hostname }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.public.hostname }}
    {{- end }}
    kubernetes.io/ingress.class: {{ $ingress_class }}

    {{- if eq $ingress_class "alb" }}
    # AWS ALB ingress (alb)
    # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/ingress/annotations/
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=false
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=4000 # max=4000
    #  Health check path annotations
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "4"
    # The ARN of your SSL certificate.
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.public.sslCertArn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    # SSL Redirect Setting
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.response-403: '{"Type":"fixed-response","FixedResponseConfig":{"ContentType":"text/plain","StatusCode":"403","MessageBody":"403 Forbidden"}}'
    {{- end }}
    
    {{- if eq $ingress_class "nginx" }}
    # Nginx ingress (nginx)
    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "http_503"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/upstream-vhost: {{ quote .Values.ingress.public.hostname }}
    # Deny admin paths if admin ingress is enabled
    {{- if .Values.ingress.admin.enabled }}
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* "^/admin" {
          deny all;
          return 403;
        }
        location ~* "^/metrics" {
          deny all;
          return 403;
        }
        location ~* "^/health" {
          deny all;
          return 403;
        }
        location ~* "^/welcome" {
          deny all;
          return 403;
        }
    {{- end }}
    {{- end }}
    {{ if .Values.ingress.public.annotations }}
    {{- toYaml .Values.ingress.public.annotations }}
    {{- end }}
spec:
  defaultBackend:
    service:
      name: keycloak-proxy
      port:
        number: 443
  rules:
    {{- if eq $ingress_class "nginx" }}
    - host: {{ .Values.ingress.public.hostname }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                {{- if eq $ingress_class "alb" }}
                name: ssl-redirect
                port:
                  name: use-annotation
                {{- else }}
                name: keycloak-proxy
                port:
                  number: 443
                {{- end }}
          {{- if and .Values.ingress.admin.enabled (eq $ingress_class "alb") }}
          - path: "/admin/"
            pathType: Prefix
            backend:
              service:
                name: response-403
                port:
                  name: use-annotation
          - path: "/metrics"
            pathType: Prefix
            backend:
              service:
                name: response-403
                port:
                  name: use-annotation
          - path: "/health"
            pathType: Prefix
            backend:
              service:
                name: response-403
                port:
                  name: use-annotation
          - path: "/welcome/"
            pathType: Prefix
            backend:
              service:
                name: response-403
                port:
                  name: use-annotation
          {{- end }}
{{- end }}