cluster-autoscaler:
  extraArgs:
    aws-use-static-instance-list: true
    max-total-unready-percentage: 90
    ok-total-unready-count: 100

  rbac:
    serviceAccount:
      create: false

  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 2Gi
