---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: licenseapp-secret-store
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  labels:
    application: "licenseapp"
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.aws.region | default "us-east-1" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: licenseapp-key
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  labels:
    application: "licenseapp"
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: licenseapp-secret-store
    kind: SecretStore
  target:
    name: licenseapp-key
    creationPolicy: Owner
  data:
    - secretKey: private-key.pkcs8.b64
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName.license | default "eks/brainspace/licenseapp/key" }}
        property: "keyfile"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: licenseapp-secrets
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  labels:
    application: "licenseapp"
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: licenseapp-secret-store
    kind: SecretStore
  target:
    name: licenseapp-secrets
    creationPolicy: Owner
  data:
    - secretKey: redis_url
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName.config | default "eks/brainspace/licenseapp/key" }}
        property: "redis_url"
    - secretKey: session_secret
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName.config | default "eks/brainspace/licenseapp/key" }}
        property: "session_secret"
    - secretKey: oauth_client_id
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName.config | default "eks/brainspace/licenseapp/key" }}
        property: "oauth_client_id"
    - secretKey: oauth_client_secret
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName.config | default "eks/brainspace/licenseapp/key" }}
        property: "oauth_client_secret"
    - secretKey: oauth_metadata_url
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName.config | default "eks/brainspace/licenseapp/key" }}
        property: "oauth_metadata_url"
    - secretKey: oauth_roles
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName.config | default "eks/brainspace/licenseapp/key" }}
        property: "oauth_roles"