---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  name: licenseapp-ui
  annotations:
    {{- if .Values.ingress.hostname }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.hostname }}
    {{- end }}
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: "internal"
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=false
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=4000 # max=4000
    #  Health check path annotations
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "4"
    {{- if .Values.ingress.sslCertArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.sslCertArn }}
    {{- end }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}

spec:
  defaultBackend:
    service:
      name: licenseapp-ui
      port:
        number: 5000
  rules:
    # - host: {{ .Values.global.hostname }}
      - http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: ssl-redirect
                  port:
                    name: use-annotation
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: licenseapp-ui
                  port:
                    number: 5000