apiVersion: apps/v1
kind: Deployment
metadata:
  name: reveal-search-api-deployment
  namespace: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      deployment: reveal-search-api-deployment
  template:
    metadata:
      labels:
        deployment: reveal-search-api-deployment
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}:{{ .Values.tag }}
          args: {{ .Values.args }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.port.containerport }}
          envFrom:
          - configMapRef:
              name: {{ .Values.name }}-config
