apiVersion: apps/v1
kind: Deployment
metadata:
  name: reveal-search-api-deployment
  namespace: {{ .Values.name }}
spec:
{{/*  Comment out replicas as it's now controlled by the HPA */}}
{{/*  replicas: {{ .Values.replicaCount }} */}}
  selector:
    matchLabels:
      deployment: reveal-search-api-deployment
  template:
    metadata:
      labels:
        deployment: reveal-search-api-deployment
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
        {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}:{{ .Values.tag }}
          args: {{ .Values.args }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1500m
              memory: 4Gi
            requests:
              cpu: 667m
              memory: 2Gi
          ports:
            - containerPort: {{ .Values.port.containerport }}
          envFrom:
          - configMapRef:
              name: {{ .Values.name }}-config
{{- if .Values.PodDisruptionBudgetReveal_search_api.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.PodDisruptionBudgetReveal_search_api.name }}
spec:
  selector:
    matchLabels:
      deployment: reveal-search-api-deployment
{{- if .Values.PodDisruptionBudgetReveal_search_api.minAvailable }}
  minAvailable: {{ .Values.PodDisruptionBudgetReveal_search_api.minAvailable }}
{{- end }}
{{- if .Values.PodDisruptionBudgetReveal_search_api.maxUnavailable }}
  maxUnavailable: {{ .Values.PodDisruptionBudgetReveal_search_api.maxUnavailable }}
{{- end }}
{{- end -}}