apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reveal-search-api-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reveal-search-api-deployment
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: 40
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300
        - type: Percent
          value: 10
          periodSeconds: 300