apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" .Values.name .Values.env }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.annotations.ingress }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.annotations.scheme }}
    alb.ingress.kubernetes.io/load-balancer-name: {{ .Values.ingress.annotations.load_balancer_name }}
    alb.ingress.kubernetes.io/tags: {{ .Values.ingress.annotations.tags }}
    {{- if .Values.ingress.hostname }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.hostname }}
    {{- end }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    {{- if .Values.ingress.sslCertArn }}
    # The ARN of your SSL certificate.
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.sslCertArn }}
    {{- end }}
    alb.ingress.kubernetes.io/security-groups: "k8s-argo-ingress"
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=3600,routing.http.drop_invalid_header_fields.enabled=true,routing.http2.enabled=true,access_logs.s3.enabled=true,access_logs.s3.prefix=ingress_logs/{{ printf "%s-%s" .Values.name .Values.env }}-ingress/{{ printf "%s-%s" .Values.name .Values.env }}-ingress,access_logs.s3.bucket={{ .Values.ingress.logBucket }}
    alb.ingress.kubernetes.io/target-group-attributes: load_balancing.algorithm.type=least_outstanding_requests,deregistration_delay.timeout_seconds=30
    alb.ingress.kubernetes.io/success-codes: "200,400"
    alb.ingress.kubernetes.io/healthcheck-path: /graphql
  labels:
    app: {{ printf "%s-%s" .Values.name .Values.env }}
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.ingress.labels.component }}
spec:
  defaultBackend:
    service:
      name: reveal-search-api-service
      port:
        number: {{ .Values.service.port }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reveal-search-api-service
                port:
                  number: {{ .Values.service.port }}
