apiVersion: v1
kind: Service
metadata:
  name: reveal-search-api-service
spec:
  selector:
    deployment: reveal-search-api-deployment
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP