---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.name }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.serviceAccount.irsa }}"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: argo
  namespace: {{ .Values.name }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.serviceAccount.irsa }}"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: spark
  namespace: {{ .Values.name }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.serviceAccount.irsa }}"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: spark
  namespace: spark
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.serviceAccount.irsa }}"
