vpa:
  recommender:
    image:
      repository: k8s.gcr.io/autoscaling/vpa-recommender
      tag: "0.9.2" #  This tag supports autoscaling.k8s.io/v1beta2. Prometheus Helm chart VPA only supports autoscaling.k8s.io/v1beta2 hence we are aligning both
    nodeSelector:
      kubernetes.io/os: linux

  updater:
    image:
      repository: k8s.gcr.io/autoscaling/vpa-updater
      tag: "0.9.2" #  This tag supports autoscaling.k8s.io/v1beta2. Prometheus Helm chart VPA only supports autoscaling.k8s.io/v1beta2 hence we are aligning both
    nodeSelector:
      kubernetes.io/os: linux
