{{- if .Values.msa_perms.serviceAccount }}
{{- if .Values.msa_perms.serviceAccount.roleArn }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: msa-perms-sa
  namespace: {{ .Values.global.namespace | default .Release.Name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.msa_perms.serviceAccount.roleArn }}

{{- end }}{{- end }}