{{- if eq  .Values.secrets.provider "external-secrets" }}
{{- if eq  .Values.secrets.externalSecrets.provider "aws" }}
# Using AWS SecretsManager
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: msa-perms-secret-store
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secrets.externalSecrets.aws.region | default "us-east-1" }}

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: msa-perms-secrets
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: msa-perms-secret-store
    kind: SecretStore
  target:
    name: msa-perms-secrets
    creationPolicy: Owner
  data:
    - secretKey: proc_sql_username
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.processing | default "eks/sqlcluster-sa/processing" }}
        property: "username"
    - secretKey: proc_sql_password
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.processing | default "eks/sqlcluster-sa/processing" }}
        property: "password"
    - secretKey: proc_sql_hostname
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.processing | default "eks/sqlcluster-sa/processing" }}
        property: "hostname"
    - secretKey: review_sql_username
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.review | default "eks/sqlcluster-sa/review" }}
        property: "username"
    - secretKey: review_sql_password
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.review | default "eks/sqlcluster-sa/review" }}
        property: "password"
    - secretKey: review_sql_hostname
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.review | default "eks/sqlcluster-sa/review" }}
        property: "hostname"
    - secretKey: task_queue_sql_username
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.taskq | default "eks/sqlcluster-sa/taskq" }}
        property: "username"
    - secretKey: task_queue_sql_password
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.taskq | default "eks/sqlcluster-sa/taskq" }}
        property: "password"
    - secretKey: task_queue_sql_hostname
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.taskq | default "eks/sqlcluster-sa/taskq" }}
        property: "hostname"
{{- end }}
{{- end }}