global:
  namespace: actions-runner-controller
  NoNamespace: false
  
  runners:
    # Applied to all runners
    labels: []
    # Applied to all runners unless overridden
    template:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
    autoscaler:
      # https://github.com/actions/actions-runner-controller/blob/master/docs/automatically-scaling-runners.md
      minReplicas: 0
      maxReplicas: 4
      scaleUpTriggers:
        - githubEvent:
            workflowJob: {}
            checkRun:
              types: ["created"]
              status: "queued"
          amount: 3
          duration: "5m"
      metrics: []
        # - type: PercentageRunnersBusy
        #   scaleUpThreshold: '0.75'
        #   scaleDownThreshold: '0.25'
        #   scaleUpFactor: '2'
        #   scaleDownFactor: '0.5'
        # - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
        #   repositoryNames:
        #     - "ORG/REPO"

authSecret:
  name: controller-manager
  key: eks/github

githubWebhookServer:
  ingress:
    hostname: github-actions-controller.domain.com
    sslCertArn: ""
    AllowedCIDRBlocks:
      - 140.82.112.0/20
      - 192.30.252.0/22
    annotations: {}

actions-runner-controller:
  authSecret:
    enabled: true
    create: false
    name: controller-manager
  serviceAccount:
    create: true
    name: actions-runner-controller-sa
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  podDisruptionBudget:
    enabled: false

  githubWebhookServer:
    enabled: true
    secret:
      enabled: true
      create: false
      name: controller-manager
    serviceAccount:
      create: true
      name: actions-runner-webhook-sa
    resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
    nodeSelector:
      kubernetes.io/os: linux
      kubernetes.io/arch: amd64
    ingress:
      enabled: false