{{- if eq  .Values.secrets.provider "external-secrets" }}
{{- if eq  .Values.secrets.externalSecrets.provider "aws" }}
# Using AWS SecretsManager
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: review-automation-secret-store
  namespace: {{ .Values.namespace | default .Release.Name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secrets.externalSecrets.aws.region | default "us-east-1" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: review-automation-secrets
  namespace: {{ .Values.namespace | default .Release.Name }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: review-automation-secret-store
    kind: SecretStore
  target:
    name: review-automation-secrets
    creationPolicy: Owner
  data:
    - secretKey: task_sql_host
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.review_task_queue_database }}
        property: "hostname"

    - secretKey: task_sql_username
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.review_task_queue_database }}
        property: "username"

    - secretKey: task_sql_password
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.review_task_queue_database }}
        property: "password"

    - secretKey: rabbitmq_username
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.rabbitmq }}
        property: "username"

    - secretKey: rabbitmq_password
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.rabbitmq }}
        property: "password"

    - secretKey: rabbitmq_url
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.rabbitmq }}
        property: "url"

{{- end }}
{{- end }}