---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: review-automation
rules:
  - apiGroups: [ "", "apps", "batch" ]
    resources: [ "deployments", "jobs", "pods", "secrets",  "configmaps" ]
    verbs: [ "*" ]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: review-automation
  namespace: "{{ .Values.namespace }}"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: review-automation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: review-automation
subjects:
- kind: ServiceAccount
  name: review-automation
  namespace: "{{ .Values.namespace }}"
