apiVersion: apps/v1
kind: Deployment
metadata:
  name: reveal-ai-api
  namespace: {{.Values.global.namespace}}
spec:
  selector:
    matchLabels:
      app: deployment-reveal-ai-api
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deployment-reveal-ai-api
      {{- if .Values.global.reloadOnUpgrade }}
      annotations:
        timestamp: {{ now | quote }}
      {{- end }}
    spec:
      nodeSelector:
        {{- toYaml .Values.frontend.nodeSelector | nindent 8 }}
      {{- if .Values.frontend.volumes }}
      volumes:
        {{- toYaml .Values.frontend.volumes | nindent 8 }}
      {{- end }}
      containers:
        - image: {{.Values.frontend.image}}:{{.Values.frontend.tag}}
          ports:
            - containerPort: 80
          env:
            {{if .Values.frontend.env}}
            {{- toYaml .Values.frontend.env | nindent 12 }}
            {{- end }}
            - name: "hostname"
              value: "https://{{.Values.ingress.hostname}}"
          imagePullPolicy: Always
          name: reveal-ai-api
          {{- if .Values.frontend.resources }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- else }}
          # Default resource requests/limits
          resources:
            requests:
              cpu: 1000m
              memory: 4096Mi
            limits:
              cpu: 2000m
              memory: 8192Mi
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          {{- if .Values.frontend.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.frontend.volumeMounts | nindent 10 }}
          {{- end }}
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      tolerations:
        {{- toYaml .Values.frontend.tolerations | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: service-reveal-ai-api
  namespace: {{.Values.global.namespace}}
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /rest/api/version

spec:
  selector:
    app: deployment-reveal-ai-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
{{- if .Values.frontend.PodDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.frontend.PodDisruptionBudget.name }}
  namespace: {{.Values.global.namespace}}
spec:
  selector:
    matchLabels:
      app: deployment-reveal-ai-api
{{- if .Values.frontend.PodDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.frontend.PodDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.frontend.PodDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.frontend.PodDisruptionBudget.maxUnavailable }}
{{- end }}
{{- end -}}