apiVersion: apps/v1
kind: Deployment
metadata:
  name: reveal-ai-ai
  namespace: {{.Values.global.namespace}}
spec:
  selector:
    matchLabels:
      app: deployment-reveal-ai
  progressDeadlineSeconds: 600
  replicas: {{ .Values.ai.replicaCount | default 2 }}
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deployment-reveal-ai
      {{- if .Values.global.reloadOnUpgrade }}
      annotations:
        timestamp: {{ now | quote }}
      {{- end }}
    spec:
      nodeSelector:
        {{- toYaml .Values.ai.nodeSelector | nindent 8 }}
      {{- if .Values.ai.volumes }}
      volumes:
        {{- toYaml .Values.ai.volumes | nindent 8 }}
      {{- end }}
      containers:
        - image: {{.Values.ai.image}}:{{.Values.ai.tag}}
          env:
            {{- toYaml .Values.ai.env | nindent 10 }}
          imagePullPolicy: Always
          name: reveal-ai
          resources:
            {{- toYaml .Values.ai.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          {{- if .Values.ai.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.ai.volumeMounts | nindent 10 }}
          {{- end }}
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      tolerations:
        {{- toYaml .Values.ai.tolerations | nindent 8 }}
{{- if .Values.ai.PodDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.ai.PodDisruptionBudget.name }}
  namespace: {{.Values.global.namespace}}
spec:
  selector:
    matchLabels:
      app: deployment-reveal-ai
{{- if .Values.ai.PodDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.ai.PodDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.ai.PodDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.ai.PodDisruptionBudget.maxUnavailable }}
{{- end }}
{{- end -}}