---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nia-worker
  namespace: {{.Values.global.namespace}}
spec:
  selector:
    matchLabels:
      app: deployment-nia-worker
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deployment-nia-worker
      {{- if .Values.nia.reloadOnUpgrade }}
      annotations:
        timestamp: {{ now | quote }}
      {{- end }}
    spec:
      nodeSelector:
        {{- toYaml .Values.nia.nia_worker.nodeSelector | nindent 8 }}
      containers:
      - image: {{.Values.nia.nia_worker.image}}:{{.Values.nia.nia_worker.tag}}
        ports:
        - containerPort: 443
        env:
          {{- with .Values.nia.env }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.nia.nia_worker.env }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
        resources:
          {{- if .Values.nia.nia_worker.resources }}
            {{- toYaml .Values.nia.nia_worker.resources | nindent 12}}
          {{- else }}
          requests:
            memory: 500Mi
          limits:
            memory: 4000Mi
          {{- end }}
        imagePullPolicy: Always
        name: nia-worker
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      tolerations:
        {{- toYaml .Values.nia.nia_worker.tolerations | nindent 8 }}
{{- if .Values.nia.nia_worker.PodDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.nia.nia_worker.PodDisruptionBudget.name }}
spec:
  selector:
    matchLabels:
      app: deployment-nia-worker
{{- if .Values.nia.nia_worker.PodDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.nia.nia_worker.PodDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.nia.nia_worker.PodDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.nia.nia_worker.PodDisruptionBudget.maxUnavailable }}
{{- end }}
{{- end -}}