{{- if .Values.persistentVolumes.enabled }}
{{- range .Values.persistentVolumes.definitions }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.global.namespace }}
  {{- if .annotations }}
  annotations:
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
  {{- if .labels }}
  labels:
      {{- range $key, $value := .labels }}
      {{ $key }}: {{ $value }}
      {{- end }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .storageClass }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
{{- end }}