{{- if eq  .Values.secrets.provider "external-secrets" }}
{{- if eq  .Values.secrets.externalSecrets.provider "aws" }}
# Using AWS SecretsManager
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: review-secret-store
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  provider:
    aws:
      service: SecretsManager
      {{- if .Values.secrets.serviceAccount }}
      {{- if .Values.secrets.serviceAccount.roleArn }}
      role: {{ .Values.secrets.serviceAccount.roleArn | quote }}
      {{- end }}{{- end }}
      region: {{ .Values.secrets.externalSecrets.aws.region | default "us-east-1" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: review-secrets
  namespace: {{ .Values.global.namespace | default .Release.Name }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: review-secret-store
    kind: SecretStore
  target:
    name: review-secrets
    creationPolicy: Owner
  data:
    - secretKey: databaseServer
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.reviewDatabase }}
        property: "databaseServer"

    - secretKey: userManagementDB
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.reviewDatabase }}
        property: "userManagementDB"

    - secretKey: AuthMethod
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.reviewDatabase }}
        property: "AuthMethod"

    - secretKey: SqlUsername
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.reviewDatabase }}
        property: "SqlUsername"

    - secretKey: SqlPassword
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.reviewDatabase }}
        property: "SqlPassword"

    # Needs to be [0-9A-Z]{48}
    - secretKey: websiteDecryptionKey
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.reviewWebEncryption }}
        property: "websiteDecryptionKey"

    # Needs to be [0-9A-Z]{128}
    - secretKey: websiteValidationKey
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.aws.secretName.reviewWebEncryption }}
        property: "websiteValidationKey"

{{- end }}
{{- end }}