yunikorn:
  operatorPlugins: general,spark-k8s-operator

  service:
    type: ClusterIP
    port: 9080
    port_web: 9889

  # When true, the admission controller will be installed along with the scheduler.
  # When false, the admission controller will not be installed.
  # Once the admission controller is installed, all traffic will be routing to yunikorn.
  embedAdmissionController: false
