name: Lint and Test Charts

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'charts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.3 # renovate: datasource=github-releases depName=helm packageName=helm/helm

      - uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5 # tag=v4.2.0
        with:
          python-version: 3.7

      - name: Install chart-testing
        uses: helm/chart-testing-action@09ed88797198755e5031f25be13da255e7e33aad # tag=v2.3.0
        with:
          version: v3.7.0 # renovate: datasource=github-releases depName=chart-testing packageName=helm/chart-testing

      - name: Run lint
        run: ct lint --config .github/ct.yaml

  # lint-docs:
  #   runs-on: ubuntu-latest
  #   needs: lint-chart
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Run helm-docs
  #       run: .github/helm-docs.sh
  # kubeval-chart:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - lint-chart
  #     - lint-docs
  #   strategy:
  #     matrix:
  #       k8s:
  #         - v1.12.10
  #         - v1.13.12
  #         - v1.14.10
  #         - v1.15.11
  #         - v1.16.8
  #         - v1.17.4
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Run kubeval
  #       env:
  #         KUBERNETES_VERSION: ${{ matrix.k8s }}
  #       run: .github/kubeval.sh